### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by QC-L** [cabbage9/cn-vitepress#1]
# 翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
>
> 2. 翻译及贡献规范请参考 [vite 中文文档](https://github.com/vitejs/docs-cn/wiki)

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] inedx

领取过：

* [ ] inedx (@QC-L)

领取过，已完成：

* [x] inedx (@QC-L) #2

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
index | inedx | @QC-L | 2021.05.18 - 2021.05.20 | -
```

示例效果：

Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
index | index | @QC-L | 2021.05.18 - 2021.05.20 | -

当完成时，请修改自己的认领评论，添加 PR 信息：

Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
index | index | @QC-L | 2021.05.18 - 2021.05.20 | #2

## 任务认领列表

Todo List:

- [x] [index](https://github.com/docschina/vitepress-docs-cn/tree/main/index.md) (@ryanmoyo)#5
- [x] [guide](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/)
  - [x] [api](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/api.md) (@ryanmoyo) [commit history](https://github.com/docschina/vitepress-docs-cn/commit/1ed1d869f23ce5535c92debfa56ae495a9f96215#diff-ac07089258ba956438fe416375f2d0fa45676260e905c4c9b5c30dbc7b84d483)
  - [x] [assets](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/assets.md)(@KimYangOfCat )#6
  - [x] [configuration](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/configuration.md)(@KimYangOfCat )#6
  - [x] [deploy](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/deploy.md)(@watonyweng ) #10 
  - [x] [differences-from-vuepress](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/differences-from-vuepress.md)(@KimYangOfCat )#6
  - [x] [frontmatter](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/frontmatter.md)(@ryanmoyo) #13 
  - [x] [getting-started](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/getting-started.md) (@QC-L) #2 
  - [x] [global-component](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/global-component.md)(@watonyweng)#7
  - [x] [theming](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/theming.md)(@ryanmoyo) #13 
  - [x] [markdown](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/markdown.md)(@ryanmoyo) #13 
  - [x] [using-vue](https://github.com/docschina/vitepress-docs-cn/tree/main/guide/using-vue.md) (@watonyweng) #8
- [x] [config](https://github.com/docschina/vitepress-docs-cn/tree/main/config/)
  - [x] [homepage](https://github.com/docschina/vitepress-docs-cn/tree/main/config/homepage.md) (@ryanmoyo) #3 
  - [x] [algolia-search](https://github.com/docschina/vitepress-docs-cn/tree/main/config/algolia-search.md)(@ryanmoyo )#5
  - [x] [basics](https://github.com/docschina/vitepress-docs-cn/tree/main/config/basics.md)(@ryanmoyo )#5
  - [x] [carbon-ads](https://github.com/docschina/vitepress-docs-cn/tree/main/config/carbon-ads.md)(@ryanmoyo )#5

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide | getting-started | @QC-L | 2021.06.15 - 2021.06.16 | #2

**Comment by eggx8** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
config| homepage | @ryanmoyo | 2021.06.15 - 2021.06.15 | #3

**Comment by eggx8** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
config | algolia-search | @ryanmoyo | 2021.06.30 - 2021.06.30 | #5 
config | carbon-ads | @ryanmoyo | 2021.06.30 - 2021.06.30 | #5 
config | basics | @ryanmoyo | 2021.06.30 - 2021.06.30 | #5

**Comment by eggx8** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
index | index | @ryanmoyo  | 2021.07.01 |  #5

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide | configuration  | @KimYangOfCat | 2021.08.29 - 2021.08.29 | #6 
guide | assets| @KimYangOfCat | 2021.08.29 - 2021.08.29 | #6 
guide | differences-from-vuepress | @KimYangOfCat | 2021.08.29 - 2021.08.29 | #6

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| guide | global-component | @watonyweng | 2021.09.06 - 2021.09.08 | #7 |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| guide | using-vue | @watonyweng | 2021.09.10 - 2021.09.12 | #8 |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| guide | deploy | @watonyweng | 2021.09.18 - 2021.09.21 | #10 |

**Comment by eggx8** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide | frontmatter | @ryanmoyo | 2021.09.24 | #13 
guide | markdown | @ryanmoyo | 2021.09.24 | #13 
guide | theming | @ryanmoyo | 2021.09.24 | #13
